
version: "3"

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - "./backend/:/app/"
    restart: always
    networks:
      - my_network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - inplace_db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  inplace_db_data: {}
